# the order in this list dictates the order in which these modules will be activated
modules:
  - 'users',
  - 'user_management',
  - 'commons',
  - 'file',
  - 'i18n',
  - 'fileupload',
  - 'theming',
  - 'wysiwyg',
  - 'node'
file_directories: {
  private: 'custom/files/private',
  public: 'custom/files/public'
  }
module_directories: []

allow_hidden_files: False
# Setting the above option to true will allow access to files
# starting with a '.' via the file handler/url
# it is highly recommended to NOT set this flag to true!

allow_indexing: True
browser_caching: False
hashing_algorithm: 'sha256'
hashing_rounds: 100000
hash_lengt: 64
salt_length: 16
default_theme: 'default_theme'
default_admin_theme: 'admin_theme'

# 0:LOG_WARNINGS, 1:LOG_ERRORS, 2:THROW_ERRORS, 3:THROW_ALL
logging_level: 3

server: {
  port: 9012,
  host: 'localhost',
  ssl_port: 9443
}

# 0:TESTING, 1:DEBUG, 2:PRODUCTION
RUNLEVEL = 0
i18n_support_enabled: False
supported_languages: {
  en_us: 'english (us)',
  en_gb: 'english (gb)',
  de: 'german',
  fr: 'french'
  }
base_language: 'en_us'
daefault_language: 'en_us'

# 0:MULTI_TABLE, 1:TREE
pathmap_type: 0
logfile: 'app.log'
middleware:
  - 'dycc.middleware.alias.Middleware',
  - 'dycm.users.middleware.AuthorizationMiddleware',
  - 'dycm.theming.middleware.FileHandler',
  - 'dycm.file.PathHandler',
  - 'dycc.middleware.trailing_slash.RemoveTrailingSlash',
  - 'dycc.middleware.ssl.ConditionalSSLRedirect',
  - 'dycc.middleware.rest.JSONTransform',
  - 'dycm.theming.middleware.Middleware'

anti_csrf: True
default_headers: {
  Content-Type: 'text/html; charset=utf-8',
  Cache-Control: 'no-cache'
  }

# 0:WSGI, 1:PLAIN
server_type: 0
propagate_errors: True

http_enabled: True
https_enabled: False
ssl_certfile: '../dynamic-content.org.crt'
ssl_keyfile: '../dynamic-content.org.key'
use_login_page: True