language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy3"
install:
    - pip install --upgrade -r requirements.txt
script: PYTHONPATH=./dynamic_content nosetests ./tests
sudo: false
os:
  - linux
  - osx
