language: python
python:
  - "3.4"
  - "pypy3"
install:
    - mkdir libs
    - pip install --upgrade -r requirements.txt
script:
    - python -OO -m unittest discover -v -s tests
    - pypy3 -OO -m unittest discover -v -s tests
sudo: false
