language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy3"
install:
    - mkdir libs
    - pip install --target libs --upgrade -r requirements.txt
env:
    - PYTHONPATH=./libs
script: nosetests
sudo: false
os:
  - linux
  - osx
