modules:
  - 'users'
  - 'user_management'
  - 'commons'
  - 'file'
  - 'i18n'
  - 'fileupload'
  - 'theming'
  - 'wysiwyg'
  - 'node'
  - 'admin'

middleware:
  - 'framework.middleware.alias.Middleware'
  - 'dycm.users.middleware.AuthorizationMiddleware'
  - 'dycm.theming.middleware.FileHandler'
  - 'dycm.file.PathHandler'
  - 'framework.middleware.rewrite.RemoveTrailingSlash'
  - 'framework.middleware.ssl.ConditionalRedirect'
  - 'framework.middleware.rest.JSONTransform'
  - 'dycm.theming.middleware.Middleware'

file_directories: {
  private: 'files/private',
  public: 'files/public',
}

import:
  - 'demo_app'

allow_indexing: True
ssl_certfile: "../dynamic-content.org.crt"
ssl_keyfile: "../dynamic-content.org.key"

default_theme: 'default_theme'
default_admin_theme: 'admin_theme'

use_login_page: True

i18n_support_enabled: False
supported_languages: {
  en_us: 'english (us)',
  en_gb: 'english (gb)',
  de: 'german',
  fr: 'french'
  }
base_language: 'en_us'
default_language: 'en_us'

database: {
  type: 'sqlite',
  name: ':memory:'
}

runlevel: 0

# 0:FULL, 1:STANDARD, 2:FRAMEWORK
distribution: 0